updates.ignore = [
  # `kafka-journal` is bound to Cassandra 3.x driver, 4.x has significantly different architecture
  { groupId = "com.datastax.cassandra", artifactId = "cassandra-driver-core" },

  # block Confluent's version of `kafka-client`
  { groupId = "org.apache.kafka", artifactId = "kafka-clients", version = { suffix = "-ce" } },

  # block akka updates after version 2.6.21 (due to their license change: https://akka.io/bsl-license-faq)
  { groupId = "com.typesafe.akka" }
]
