name: CI

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    uses: evolution-gaming/scala-github-actions/.github/workflows/ci.yml@c5149c701542c233773574b6428155377b36eea8 # v7.1.0
