name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.18
          - 3.3.8

    steps:
      - uses: actions/checkout@v4

      - uses: coursier/cache-action@v6

      - name: setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'sbt'

      - name: setup SBT
        uses: sbt/setup-sbt@v1

      - name: check code ${{ matrix.scala }}
        run: sbt "++${{ matrix.scala }}; clean; check"

      - name: build ${{ matrix.scala }}
        run: sbt "++${{ matrix.scala }}; clean; coverage; test; coverageAggregate"

      - name: test coverage
        if: success()
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          file: target/out/jvm/scala-${{ matrix.scala }}/kafka-journal-root/coverage-report/cobertura.xml
          format: cobertura
          flag-name: Scala ${{ matrix.scala }}
