name: Dependency graph

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  submit:
    uses: evolution-gaming/scala-github-actions/.github/workflows/dependency-graph.yml@61f111a4472fde7b63e5921ac8a238f22d1bb028 # v7.0.1
