name: Publish Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # can delete tag on failed release attempt

jobs:
  release:
    uses: evolution-gaming/scala-github-actions/.github/workflows/release.yml@61f111a4472fde7b63e5921ac8a238f22d1bb028 # v7.0.1
    secrets: inherit
