name: Publish Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # can delete tag on failed release attempt

jobs:
  release:
    uses: evolution-gaming/scala-github-actions/.github/workflows/release.yml@999c04ccae0d79a8a0c12ed7d71136762b2ae8c1 # v7.1.0
    secrets: inherit
